#server:
#  port: 8015
#
#spring:
#  application:
#    name: guli-coupon
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.220.128:3306/gulimall_sms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: c3ff9096-0c2e-47a7-b4ec-469be8dffe67
#
#
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-tyoe: auto


